mls:
  clb:
    - company: Moo Moo Express Car Wash
      name: Moo Moo Express Clean Sheets = Clean Car
      promo_type: free_gifts
      promo_code:
      source_url: https://www.columbuscrew.com/supporters/promotions
      redemption_limiter: monthly
      redemption_count: 0
      hours_valid: 48
      timing_parameters:
        minutes_before: 60
      api_parameters: {}
      timing_methods:
        - home?
      api_methods:
        - home?
        - perfect_defence?
    - company: Tim Hortons
      name: Tim Hortons - Free Coffee
      promo_type: free_gifts
      promo_code:
      source_url: https://www.columbuscrew.com/supporters/promotions
      redemption_limiter:
      redemption_count: 0
      hours_valid: 24
      timing_parameters: {}
      timing_methods:
      api_parameters:
        goals_count: 1
      api_methods:
        - goal_count_equal_or_above?
    - company: Donatos
      name: Donatos - Victory Pizza
      promo_type: coupon_codes
      promo_code: CREW
      source_url: https://www.columbuscrew.com/supporters/promotions
      redemption_limiter:
      redemption_count: 0
      hours_valid: 24
      timing_parameters: {}
      api_parameters: {}
      timing_methods:
      api_methods:
        - won?
nhl:
  ana:
    - company: Chick-fil-A
      name: Chick-fil-A SoCal Goals for Chicken
      promo_type: free_gifts
      promo_code:
      source_url: https://www.nhl.com/ducks/fans/partner-promotions
      redemption_limiter:
      redemption_count: 0
      hours_valid: 72
      timing_parameters: {}
      api_parameters:
        goals_count: 5
      timing_methods:
      api_methods:
        - home?
        - goal_count_equal_or_above?
    - company: McDonalds
      name: Get $2 Sausage Egg & Cheese McGriddles When Ducks Win
      promo_type: cash_discount
      promo_code:
      source_url: https://www.nhl.com/ducks/fans/partner-promotions
      redemption_limiter:
      redemption_count: 0
      hours_valid: 24
      timing_parameters: {}
      api_parameters: {}
      timing_methods:
      api_methods:
        - home?
        - won?
  cbj:
    - company: Moo Moo Express Car Wash
      name: Moo Moo Express Car Wash 3rd Period Goal
      promo_type: free_gifts
      promo_code:
      source_url: https://www.nhl.com/bluejackets/fans/gameday-central
      redemption_limiter: seasonal
      redemption_count: 1
      hours_valid: 24
      timing_parameters:
        minutes_before: 60
      api_parameters:
        period: 3
      timing_methods:
        - home?
      api_methods:
        - home?
        - scored_in?
    - company: Jet's Pizza
      name: Jet's Pizza Score Twice Half Price
      promo_type: order_discounts
      promo_code: CBJ50
      source_url: https://www.nhl.com/bluejackets/fans/gameday-central
      redemption_limiter:
      redemption_count: 0
      hours_valid: 24
      timing_parameters: {}
      api_parameters:
        goals_count: 2
      timing_methods: []
      api_methods:
      - goal_count_equal_or_above?
    - company: Roosters
      name: Free Roosters Chili
      promo_type: free_gifts
      promo_code:
      source_url: https://www.nhl.com/bluejackets/fans/gameday-central
      redemption_limiter:
      redemption_count: 0
      hours_valid: 24
      timing_parameters: {}
      api_parameters:
        goals_count: 3
      timing_methods: []
      api_methods:
      - home?
      - goal_count_equal_or_above?
    - company: Tim Hortons
      name: Tim Hortons - Free Coffee
      promo_type: free_gifts
      promo_code:
      source_url: https://www.nhl.com/bluejackets/fans/gameday-central
      redemption_limiter: seasonal
      redemption_count: 0
      hours_valid: 24
      timing_parameters: {}
      api_parameters:
        goals_count: 3
      timing_methods: []
      api_methods:
      - home?
      - won?
